version: 0.0
os: linux

# Define the files to be transferred to the EC2 instance
files:
  - source: /                # This is the root of the project or build artifact directory
    destination: /tmp/app     # Temporary location where the files will be placed

# Define the hooks for the deployment lifecycle
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 180
      runas: root

  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 180
      runas: root

  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 180
      runas: root

  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 180
      runas: root

  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 180
      runas: root

